### ISSUE TITLE
Feature request: "allow certain code sections to be excluded from 'evaluate all' command.

### ISSUE THREAD

**Issue by behrica** [JonyEpsilon/gorilla-repl#179]
My use-case for this is "caching".

I work on an analysis where a certain steps takes very long.
But on the same time, I would like to execute "evaluate-all-segments" from time to time, just to be sure, that the whole document still works.

I noticed that by using the "memoize" function in clojure I can easely create a "caching" version of my long-running functions.

So I would end in three code blocks:

````clojure
(defn a-long-running-function
....)
`````

````clojure
(def  a-long-running-function-memo (memoize a-long-runninf-function))
`````

````clojure
(def  data  (a-long-running-function-memo))
`````

If I have something like this. I could repeatedly execute the third code block, and it would execute my long-running-function only ones (and then take the cached result).

So I could use "eveluate all" withoung getting longs waits... 
But unfortunately the re-evaluation of code block 2)  will create a new memoized function and so invalidate the cache.
As a workarround I could (by-hand) re-evaluate all code blocks (except the 2.).
So it would be nice to automate this. So mark a code block as "frozen" or something.

In this state it would be excluded from "evaluate all".

I am not sure how IPhyton solves this ?
I found some discussion here: http://stackoverflow.com/questions/19309287/how-to-intermittently-skip-certain-cells-when-running-ipython-notebook

**Comment by behrica** [comment]
I believe that Gorilla Repl should address the "cache feature" at a certain point.

By using "memoize" and implementing this feature rqeuest we could go rather far.
It should allows arbitrary caching (in memory) without implementing anything in Gorilla for caching.

**Comment by JonyEpsilon** [comment]
One of my goals for Gorilla was to keep it as simple as is possible, but still be usable. I've resisted adding features to the notebook, in particular ones that involve cell-level metadata. So, I think I'd resist having exceptions to "evaluate all" as well.

As you rightly point out though, I don't think this actually needs Gorilla support [And, if I try and justify my drive to keep Gorilla simple: I think many of the features that **could** be added to the notebook don't actually need to be in there. Most of them could be better implemented in the language itself.] A really neat little library would be one that took calls of the form:

```clojure
(with-cache (my function call) "cache.file")
```

checked for the existence of the cache file, and loaded it if it exists, otherwise called the function and saved the results. Writing this as a library would mean that it could be used from the command-line REPL etc too.

So, I guess my feeling is that this would be a great thing to write, but it doesn't belong in Gorilla!

**Comment by behrica** [comment]
Regarding the cache, I might agree that it should be outside of Gorilla.

Regarding my initial request, I believe that "evaluation of code cells" is a concern of Gorilla.
Currently it supports 2 ways of evaluating code cells:
 
  - Current cell
  - All cells

I am not sure, if this covers all use cases.
I see a need for things like "evaluate all cells below current cell".

Coming back to cache: Even with library support as you described, there might be a need to "reset" or "invalidate" a cache. How to do this without support in Gorilla (or change the code ones, for resetting it) ? The caching of evaluated cells is a complex problem, as it depends on dependencies between cells which are not expressed in code.

Knitr has a very complex solution for this, which Gorilla should probably not adopt.

I still think that my proposal to have a way to "mark a cell as being excluded from the evaluate-all" could make sense.

While doing data analysis on larger data, I see my self always juggling between evaluate (or not re-evaluate) pieces of code, in order to not re-evaluate time consuming pieces of the analysis, if not needed.

@JonyEpsilon  How do you personally handle the problem of cells which take a long time to evaluate ?

**Comment by JonyEpsilon** [comment]
Hi @behrica,

 I think the question here is getting the right balance between features and keeping it simple. My view this far on these matters in Gorilla, which I think I want to stick with, is to go with "as simple as is possible". I think there are two reasons for this: one, because I want to make sure Gorilla is easy to maintain in the limited time I have for it; and two because I like the very simple, predictable nature of it.

So while I agree that "marking a cell to be excluded" would be a feature that could be useful, I think my view on it is that it isn't essential, and makes things a fair amount less simple to implement (because we'd have to include a way to persist and edit cell-level metadata), and less simple to think about (because the evaluation now depends on cell metadata).

For the "evaluate all below" command, I tend to do this by holding down shift and enter for a while, which is quite easy once you get used to it. So, my gut feeling is that a separate command isn't really needed. But I wouldn't be against adding it if there's demand.

Personally, for long running cells I use a pretty primitive system of spitting and slurping the intermediate results, and commenting bits of the code. It's not very elegant, but it works ok. So I'll have something like (missing out the prints and reads)

```clojure
(def d (do-long-running-thing))
(spit "file" d)
;;(def d (slurp "file))
```

And then once I've run it I change (manually) the comments to

```clojure
;;(def d (do-long-running-thing))
;;(spit "file" d)
(def d (slurp "file))
```

Like I say, it's primitive, but I find it works ok. In a couple of worksheets where I do this a lot, I've used a "recalculate" var as a flag and put the above lines in `if` forms.

I could see a little library so that the above was:

```clojure
(with-cache (do-long-running-thing) "file")
```

being really useful. And maybe the re-running and re-saving the cache could be as easy as adding

```clojure
(with-cache (do-long-running-thing) "file" :recalculate)
```

?

Jony

**Comment by behrica** [comment]
I understand your arguments.
I specially like the last syntax for the cache. If I find some time I have a look at this.
