### ISSUE TITLE
library for gorilla specific repl functions ?

### ISSUE THREAD

**Issue by behrica** [JonyEpsilon/gorilla-repl#181]
By using Gorilla repl for data analysis, I frequency see the need for two specific functionalities.

Those are:

1. Caching
2. Show the memory the objects are using

In my last data analysis I created a function which implements the second.
The idea is to:

Show a table with one row per var of the current names space:
- var name
- if a countable object (= seq, array, String ....) shows the count, if not it calls "toString()" on the object and takes the first 100 characters
- estimation of its size by serialize it to a byte array and count the bytes

I realize that this is not very precise due to the shared data structure of Clojure, but it works anyway.
But it still gives an overview over the currently created vars 
and renders rather nice in Gorilla. (see attached screenshot)
![objects](https://cloud.githubusercontent.com/assets/127361/5643441/e8ea9f8a-9658-11e4-8674-d849a00c69e8.png)

The first could just contain a little function we discussed in #179 

I will start a project here:
https://github.com/behrica/gorilla-tools

Maybe you can have a look ones something is there.

**Comment by JonyEpsilon** [comment]
Hi @behrica,

 this looks great! A comment would be that I think people who don't use Gorilla would also find this very useful - a lot of people do this sort of thing from within the command-line REPL, emacs, incanter etc. If I were you I would market it more widely than just "gorilla-tools", and call it "repl-analysis-tools", or something so that more people will use it!

I think I'll mark this issue as closed, as it doesn't need action from the Gorilla side, but do feel free to keep commenting here to keep things updated, if you like.

Jony
