### ISSUE TITLE
missing a few features: editable metadata,  json/map export,  slideshows with live coding

### ISSUE THREAD

**Issue by fredokun** [JonyEpsilon/gorilla-repl#190]
I have a very intensive use of notebook environments (Ipython, Sage, etc.) for my work, and I'm (also) a long-time lisper learning clojure  !   I really *love* the simplicity of Gorilla-repl but I miss a few features regarding my own workflow. These features are available in e.g. the Ipython notebooks:

1. the possibility to annotate the cells (blocks)  with editable (~~JSon or other~~ EDN) metadata.
For example, slide annotations for slideshows,  skipme tag for skipping when producing
a pdf,   answers when I am authoring exercises, etc.

2. the possibility to export to an easily parsable and scriptable file format (think ~~JSon, or clojure map~~ EDN)
I find it nice that a gorilla worksheet is also a clojure source file,  but I would still enjoy a more easily parsable export for later processing (especially  markdown generation for pandoc).  The metadata would play a significant role for the processing of course. For example to skip some blocks...

3. a  slidehow view in which the blocks remain editable  (think reveal.js but maybe something more "zen", in the spirit of gorilla as I see it).
Slideshows & live coding is for me a "killer feature"... excellent  for courses (it seems the students enjoy this) and not-too-boring presentations...

(sorry for the noice, these are not *actual* issues).

**Comment by JonyEpsilon** [comment]
Hi Fred,

 thanks for the comments - not noise at all, always like to hear people's views. It raises an interesting point as well, which I've been thinking about lately since one of the IPython devs questioned why not write a Clojure kernel for IPython, rather than Gorilla REPL? I think my answer to that question, which touches upon the points you mentioned, is that I don't really see Gorilla REPL as quite the same as IPython. Rather I think it makes its own design choices.

So, to address your particular points:

1. I've strenuously resisted the addition of cell- or worksheet-level metadata, and think I want to continue to do so! Not because it's not a good idea, and I appreciate that would enable a lot of different other good ideas. But just because I want to keep the core of Gorilla as simple as is possible. I think this is one of the points where I see Gorilla as taking a different path than IPython.

2. Interesting idea. Given the explicit "read" step in LISP I wonder whether this already exists though? I've never looked closely at tools.reader, but it might already do precisely what is wanted here - convert a source file into a data structure.

3. See 1 :-p . Again, I don't think this is a bad idea at all, just one that I don't see as fitting with how I want Gorilla REPL to be.

I hope I don't seem too disagreeable - once again, I don't mean to suggest these are bad ideas, just that I want to keep a clear vision of what Gorilla should be. I should say too, for the record, I think it would be a great thing to have a well supported IPython kernel for Clojure :-)


Jony

**Comment by JonyEpsilon** [comment]
So, there's been some further discussion of cell-level metadata on #192 . Might be worth reconsidering these ideas once that has shaken out.

I'm going to close this one for the moment, but feel free to comment/reopen.

**Comment by timothyrenner** [comment]
I ran across this issue when Googling for a converter to use on a project of mine. I ended up writing one - I've put it in a [gist](https://gist.github.com/timothyrenner/3902af1df1671f1f8fc3).

I'd be happy to bundle this into a library and throw it onto clojars if there isn't already a solution (or plans for one). Since I wrote it as a one-off I think it needs a little work to make it more robust; I'd welcome any feedback on that front as well.
