### ISSUE TITLE
Increase size for saving worksheet

### ISSUE THREAD

**Issue by jguhlin** [JonyEpsilon/gorilla-repl#196]
I keep getting error 413 " Request entity too large" in the JavaScript console. I'm not sure how big the file is now but the last save was 6mb. Maybe a command line option for those who large worksheets would be out of the ordinary? 

Thanks!

**Comment by jguhlin** [comment]
Apparently on line 117 of core.repl where you pass the :port and :ip options you can also pass :max-body

This is the default set by httpkit

max-body 8388608             ; max http body: 8m

I may try to dig into the gorilla repl code (finally) and add some sort of compression to save compressed worksheets, using a gzip JS implementation or something.

**Comment by JonyEpsilon** [comment]
Hi. Thanks for the report and fix, and I hope it didn't cause you to lose anything important! I think this is the same issue as in #186. The fix will definitely be in the next release, although I'm busy at the moment, so that might be a little while ...

I'm going to close this issue and leave #186 open.

Thanks,

Jony
