### ISSUE TITLE
Rendering geo data

### ISSUE THREAD

**Issue by wiseman** [JonyEpsilon/gorilla-repl#198]
Does anyone know of any work to make it possible to render geo data with gorilla?  Vega supports some geo functionality, which makes it seem doable.

Ideally, I'd like to be able to plot points, segments and polygons as overlays on Google Maps.

**Comment by JonyEpsilon** [comment]
If Vega can render it, then Gorilla will be able to show it. The easiest for experimenting is to use:

```
(gorilla-repl.vega/vega-view your-vega-data-structure)
```

You can then write functions that generate the appropriate Vega data, like the gorilla-plot functions do.

That said, I've no idea whether Vega can actually do what you need, as I've not used it for geo-data ever!

**Comment by wiseman** [comment]
Vega didn't seem to offer the features I was looking for in rendering geo data, like interactive slippy/zoomy maps w/ many choices of base map, so I wrote [leaflet-gorilla](https://github.com/wiseman/leaflet-gorilla) to create maps using the [Leaflet javascript library](http://leafletjs.com/):

![screenshot](http://i.imgur.com/r6j7qio.png)

It wasn't too hard, though it felt a bit ugly to have to write quite a lot of javascript for each rendered value just to handle ["ensure another external piece of javascript (leaflet) is loaded and then do something after we know it's loaded"](https://github.com/wiseman/leaflet-gorilla/blob/master/src/com/lemondronor/leaflet_gorilla.clj#L113)--maybe you have some thoughts on how I could handle that better, or perhaps that Gorilla could support that sort of use case for extensions.

**Comment by JonyEpsilon** [comment]
Hi John,

 sorry for the slow reply.

[BTW, the latest version of leaflet-gorilla looks amazing - motivating me to finally learn about PostGIS.]

Yeah, this is a bit awkward. I can see three sensible solutions:

- Have some mechanism for renderers to request a js file be loaded, and have the logic for it done once, in the Gorilla client rather than the plugin having to manage it.

- Just add leaflet as a dependency to the Gorilla client.

- Ignore the bit of awkwardness and leave it as it is!

Given that I'm not deluged by requests to include extra js libraries, I think the second option might be better, as it's very simple. And I don't think load time etc are really a big problem for the typical use cases for Gorilla. It does mean, I guess, that the leaflet version will be tied to the Gorilla version, but this might not be too much of a headache.

What do you think?


Jony

**Comment by wiseman** [comment]
I understand this may not be a common use case, so options #2 and #3 both seem pretty reasonable to me.  Just leaving things as they are might be slightly preferable due to imposing the small overhead only on people using leaflet-gorilla rather than all gorilla-repl users.

In the future, though (say once there is at least one other gorilla renderer that wants to insert large amounts of javascript), it might also be helpful to allow code to not only ask gorilla to load external dependencies into a page, but to insert other javascript code that can then be used by the in-browser rendering code.
