### ISSUE TITLE
webkit repl right inside intellij idea?

### ISSUE THREAD

**Issue by kindlychung** [JonyEpsilon/gorilla-repl#208]
This is an amazing project. But switching and copying/pasting code between the browser and the IDE is just tedious, why not put the repl inside the IDE? This way you can send code directly into gorilla (cmd-shift-L for loading file, cmd-shift-P for eval), and using all the editing power (paredit, autocompletion, etc) of intellij.

**Comment by JonyEpsilon** [comment]
Thanks for the kind words! I'd also love to see better integration with IDEs like IntelliJ. I don't think it will be very easy, though, as I don't think IntelliJ supports very deep integration with Webkit. I also would want to ensure that any changes that were made did not affect the ability to run Gorilla standalone, as this is very useful for server-based usage.

I'm going to close the issue as "won't fix", just because I don't think it's really possible. But I'd love to be proven wrong with a PR :-)
