### ISSUE TITLE
core.matrix support

### ISSUE THREAD

**Issue by mikera** [JonyEpsilon/gorilla-repl#47]
I would find it extremely useful and interesting if there was some `core.matrix` support in gorilla-repl

In particular the following features would be great:

 - Viewing a subset of a large matrix (some can be *very* big and don't print nicely in a regular REPL so you really need to be able to view a restricted window)
 - Visualising a matrix as a bitmap (especially useful for sparse / non-zero values)
 - Charting a N-dimensional array (as multiple lines, bars etc.)

**Comment by JonyEpsilon** [comment]
Looking back at this with hindsight of having added rendering support for a number of libraries, I think the right way to go on this is a separate rendering library (see https://github.com/JonyEpsilon/loom-gorilla for an example). That works pretty nicely, and keeps separate things separate. I think the implementation notes above are still relevant.

Going to close the issue here as I don't think this is a Gorilla issue as such.
